backend_saml_login:
    pattern: /login-saml

backend_saml_login_check:
    pattern: /login-check-saml

backend_saml_logout:
    pattern: /logout-saml

#saml_bundle:
#    resource: "@SamlBundle/Resources/config/routing.yml"